In [1]:
import numpy as np

In [5]:
my_list = [1, 2, 3, 4]
my_list*2

[1, 2, 3, 4, 1, 2, 3, 4]

##### creating numpy list

In [9]:
array = np.array(my_list)
array*2


array([2, 4, 6, 8])

##### ndim array  &  slicing

In [14]:
#arr = np.array(2)
#arr = np.array([1, 2, 3, 4])
#arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr = np.array([[[1], [2], [3]], 
                [[4], [5], [6]],
                [[7], [8], [9]]])  # -- 7    _8_(2,1,0)    9
print(arr.shape)
#arr.ndim
print(arr[2,1,0])

num = arr[0, 1, 0] + arr[1, 1, 0] + arr[2, 0, 0]
print(num)

(3, 3, 1)
8
14


In [ ]:
array = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8],
                  [9, 10, 11, 12],
                  [13, 14, 15, 16]])

print(array[2, :-1])
print(array[1:4:2])
print(array[:, :2])



[ 9 10 11]
[[ 5  6  7  8]
 [13 14 15 16]]
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]


#### Arithemic

In [11]:
ar = np.array([1.01, 2.02, 3.67, 4])
print(ar * 3 + 1)
print(np.sqrt(ar))
print(np.round(ar))



[ 4.03  7.06 12.01 13.  ]
[1.00498756 1.42126704 1.91572441 2.        ]
[1. 2. 4. 4.]


In [12]:
radii = np.array([1, 2, 3, 4])
print(np.pi * (radii**2))

[ 3.14159265 12.56637061 28.27433388 50.26548246]


### element wise arithmetic

In [16]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
print(array1**array2)
print(array1 * array2)

print(array1 + array2)


[  1  32 729]
[ 4 10 18]
[5 7 9]


### data filtering

In [23]:
scores = np.array([91, 55, 100, 67, 82, 64])
print(scores >= 67)
scores[scores < 60] = 0
print(scores)

[ True False  True  True  True False]
[ 91   0 100  67  82  64]


### broadcasting

In [30]:
a1 = np.array([[1, 2, 3, 4], [5 ,6 , 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
a2 = np.array([[1], [2], [3], [4]])
print(a1.shape, a2.shape)
print(a1 * a2)

(4, 4) (4, 1)
[[ 1  2  3  4]
 [10 12 14 16]
 [27 30 33 36]
 [52 56 60 64]]


### aggregate functions

In [2]:
a = np.array([[1, 2, 3, 4, 5],
               [6, 7, 8, 9, 10]])
print(a.sum())
print(a.mean())
print(a.std())
print(a.var())
print(a.min())
print(a.argmin())
print(a.argmax())
print(np.sum(a, axis=0))

55
5.5
2.8722813232690143
8.25
1
0
9
[ 7  9 11 13 15]


## Filtering

In [16]:
ages = np.array([[21, 17, 19, 20, 16, 30, 18, 67], 
                 [39, 22, 15, 99, 18, 19, 20, 21]])

teens = ages[ages < 18]
adults = ages[(ages >= 18) & (ages < 65)]
random = ages[~(ages < 33)]
seniors = ages[ages >= 65]
even = ages[ages % 2 == 0]

ad = np.where(ages >= 18, ages, 0)
print(teens, adults, random, seniors, even, ad)

[17 16 15] [21 19 20 30 18 39 22 18 19 20 21] [67 39 99] [67 99] [20 16 30 18 22 18 20] [[21  0 19 20  0 30 18 67]
 [39 22  0 99 18 19 20 21]]


## RNG 

In [ ]:
rng = np.random.default_rng(seed=1) #seeeeeeds
print(rng.integers(0, 1000, [4, 4]))

[[473 511 755 950]
 [ 34 144 822 948]
 [249 311 869 423]
 [273 827 256 409]]


In [164]:
np.random.seed(seed=3)
print(np.random.uniform(0, 100, (3, 3)))


[[55.07979026 70.81478226 29.09047389]
 [51.08276052 89.29469543 89.62930889]
 [12.55853105 20.72428781  5.14672033]]


In [172]:
array = np.array([1, 2, 3, 4, 5])
rng = np.random.default_rng()
rng.shuffle(array)
print(array)

[2 3 5 4 1]


In [194]:
fruits = np.array(['apple', 'banana', 'orange', 'coconut', 'porridge'])
fr2 = np.array(['🍎', '🍌', '🍊', '🥥', '🥣'])
fruit = rng.choice(fr2, (2, 4))
print(fruit)

[['🥥' '🍊' '🍎' '🥥']
 ['🍊' '🥣' '🥣' '🍎']]
